### ISSUE TITLE
color changes to #ff589e when hovered on footer icons

### ISSUE THREAD

**Issue by shivansh361** [shivansh361/Euphoria-technologies#11]

**Comment by Himanshu664** [comment]
I am working on it.

**Comment by RishiRajKhanna2511** [comment]
Can you assign it to me

**Comment by anuragyadav20062002** [comment]
can you assign it to me

**Comment by shivansh361** [comment]
@RishiRajKhanna2511 you got it wrong

**Comment by RishiRajKhanna2511** [comment]
@shivansh361 Sorry for the mistake.Can you check the changes done

**Comment by shivansh361** [comment]
Working good. Good work @RishiRajKhanna2511 @pranshuj73
