### ISSUE TITLE
Testimonial and contact us sections

### ISSUE THREAD

**Issue by shivansh361** [shivansh361/Euphoria-technologies#26]
Complete both the tasks.

- [ ] Make the cards of testimonial section like the cards of Why euphoria section

![Screenshot from 2021-10-04 14-42-21](https://user-images.githubusercontent.com/91822290/135825529-c7aa09c0-7d6b-4194-b770-b7deb8fc9359.png)

The card should move up on hover. This has to be done with the cards in testimonial seciton.

- [ ]  Make the font size of the contact us message box smaller. 1 rem.

![Screenshot from 2021-10-04 14-48-41](https://user-images.githubusercontent.com/91822290/135825956-e06b03af-d98c-46ec-9294-d73072b40b95.png)

**Comment by himalaya0035** [comment]
I would be happy to do this, please assign this to me @shivansh361

**Comment by shivansh361** [comment]
Go ahead @himalaya0035 :+1:

**Comment by himalaya0035** [comment]
👍
