### ISSUE TITLE
Create a nice logo for Euphoria Tech.

### ISSUE THREAD

**Issue by shivansh361** [shivansh361/Euphoria-technologies#8]

**Comment by KaranSinghBisht** [comment]
Hey @shivansh361, can you emphasize the type of logo required?

**Comment by shivansh361** [comment]
Logo in the form of abbreviation and light in colors

**Comment by KaranSinghBisht** [comment]
Hey @shivansh361! This is what I came up with
![Logo1](https://user-images.githubusercontent.com/69008866/136670412-c690db66-f788-446e-abf4-b3562e20f5af.png)

**Comment by shivansh361** [comment]
great . make a PR
